import logging
import uuid
from typing import List, Optional

from fastapi import HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

from api.errors import ExternalAPIError, AppError
from api.models import AnswerRequest, StartRequest, QuestionResponse, ResultResponse, FinalResponse, EvidenceSummaryItem
from db.models import InterviewSession
from infermedica.client import InfermedicaClient, InfermedicaIntegrationError
from infermedica.enums import AgeUnit, Sex
from infermedica.models import ParseRequest, Age, DiagnosisRequest, EvidenceItem, DiagnosisResponse

MAX_QUESTIONS = 2

class InterviewService:
    def __init__(self, db: Session, client: InfermedicaClient):
        self.db = db
        self.client = client

    @staticmethod
    def _build_evidence_summary(db_evidence: List[dict]) -> List[EvidenceSummaryItem]:
        """
        Helper for creating list of returned evidence summary items.

        Args:
            db_evidence (List[dict]): evidence list from database.

        Returns:
            List[EvidenceSummaryItem]: list of evidence summary items for result response model.
        """
        return [
            EvidenceSummaryItem(item_id=ev["id"], choice_id=ev["choice_id"])
            for ev in db_evidence
        ]

    async def start_interview(self, request: StartRequest) -> ResultResponse:
        """
        Creates new interview session and performs the initial symptom parsing with first diagnosis.

        Args:
            request (StartRequest): Provided patient demographics data with initial description.

        Returns:
            ResultResponse: Result of the symptom parsing and first evidence.
        """
        try:
            interview_id = str(uuid.uuid4())
            self.client.set_interview_id(interview_id)

            parse_req = ParseRequest(
                age=Age(value=request.age, unit=request.age_unit),
                sex=request.sex,
                text=request.text,
            )
            parse_resp = await self.client.parse(parse_req)

            initial_evidence_objects = [
                EvidenceItem(id=mention.id, choice_id=mention.choice_id, source="initial")
                for mention in parse_resp.mentions
            ]
            initial_evidence_dicts = [item.model_dump(mode="json") for item in initial_evidence_objects]

            db_session = InterviewSession(
                id=uuid.UUID(interview_id),  # Zabezpieczenie na atrybut .hex
                age_value=request.age,
                age_unit=request.age_unit,
                sex=request.sex,
                evidence=initial_evidence_dicts
            )
            self.db.add(db_session)
            self.db.commit()

            diag_req = DiagnosisRequest(
                age=Age(value=request.age),
                sex=request.sex,
                evidence=initial_evidence_objects
            )
            diag_resp = await self.client.diagnosis(diag_req)

            if not diag_resp.question:
                return await self._return_final(db_session, diag_req, diag_resp)

            question_item = diag_resp.question.items[0]
            question_resp = QuestionResponse(
                question_text=diag_resp.question.text,
                item_id=question_item.id,
                name=question_item.name,
                choices=question_item.choices
            )

            return ResultResponse(
                interview_id=interview_id,
                is_finished=False,
                evidence_summary=self._build_evidence_summary(initial_evidence_dicts),
                question_response=question_resp
            )

        except InfermedicaIntegrationError as e:
            logging.error(f"Infermedica API error: {e}")
            raise ExternalAPIError(str(e))
        except Exception as e:
            logging.exception("Failed to start interview:")
            raise AppError("Start: Internal server error", status_code=500)

    async def process_answer(self, interview_id: str, request: AnswerRequest) -> ResultResponse:
        """
        Provides further questions or final triage and diagnosis results based on a received answer.

        Args:
            interview_id (str): ID generated by start_interview
            request (AnswerRequest): Patient's choice related to question item ID.

        Returns:
            ResultResponse: Response containing next question or final triage and diagnosis results.
        """
        try:
            db_session = self._get_db_session(interview_id)

            current_evidence = list(db_session.evidence)
            new_evidence = {"id": request.item_id, "choice_id": request.choice_id.value, "source": "suggest"}
            current_evidence.append(new_evidence)

            db_session.evidence = current_evidence
            db_session.questions_asked += 1
            self.db.commit()

            diag_req = DiagnosisRequest(
                age=Age(value=db_session.age_value, unit=AgeUnit(db_session.age_unit)),
                sex=Sex(db_session.sex),
                evidence=[EvidenceItem(**item) for item in current_evidence]
            )

            if db_session.questions_asked >= MAX_QUESTIONS:
                return await self._return_final(db_session, diag_req)

            diag_resp = await self.client.diagnosis(diag_req)

            if not diag_resp.question:
                return await self._return_final(db_session, diag_req, diag_resp)

            question_item = diag_resp.question.items[0]
            question_resp = QuestionResponse(
                question_text=diag_resp.question.text,
                item_id=question_item.id,
                name=question_item.name,
                choices=question_item.choices
            )

            return ResultResponse(
                interview_id=interview_id,
                is_finished=False,
                evidence_summary=self._build_evidence_summary(current_evidence),
                question_response=question_resp
            )
        except Exception as e:
            logging.exception("Failed to process answer:")
            raise AppError("Answer: Internal server error", status_code=500)

    def _get_db_session(self, interview_id: str) -> InterviewSession:
        """
        Selects interview session from database based on interview_id.

        Args:
            interview_id (str): ID generated by start_interview

        Returns:
            InterviewSession: Row found in interview_sessions table.
        """
        stmt = select(InterviewSession).where(InterviewSession.id == interview_id)
        db_session = self.db.execute(stmt).scalar_one_or_none()

        if not db_session:
            raise HTTPException(status_code=404, detail="Interview session not found")

        if db_session.is_completed:
            raise HTTPException(status_code=400, detail="Interview is already completed")
        return db_session

    async def _return_final(self, db_session: InterviewSession,
                            request: DiagnosisRequest,
                            diag_resp: Optional[DiagnosisResponse] = None) -> ResultResponse:
        """
        Provides final response with triage and diagnosis results.

        Args:
            db_session (InterviewSession): Row found in interview_sessions table.
            request (DiagnosisRequest): Data parsed from patient's answer and all collected evidence items.'
            diag_resp (Optional[DiagnosisResponse]): Already collected final diagnosis results.

        Returns:
            ResultResponse: Response with triage level, received possible conditions and evidence summary.
        """
        if not diag_resp:
            diag_resp = await self.client.diagnosis(request)
        triage_resp = await self.client.triage(request)

        db_session.is_completed = True
        self.db.commit()

        final_resp = FinalResponse(
            triage_level=triage_resp.triage_level,
            conditions=diag_resp.conditions
        )

        return ResultResponse(
            interview_id=str(db_session.id),
            is_finished=True,
            evidence_summary=[EvidenceSummaryItem(item_id=item["id"], choice_id=item["choice_id"]) for item in db_session.evidence],
            final_response=final_resp
        )